package it.feriepermessi.nativeapp.domain

import it.feriepermessi.nativeapp.data.*
import java.time.LocalDate
import java.time.YearMonth
import org.junit.Assert.*
import org.junit.Test

class LeaveEngineTest {
    private val today = LocalDate.of(2026, 9, 30)
    private val engine = LeaveEngine(today)
    private fun entry(id: String, type: String, date: String, qty: Double, sim: Boolean = false): EntryEntity {
        val d = LocalDate.parse(date)
        return EntryEntity("a", id, type, date, date, qty, year = d.year, month = d.monthValue, simulated = sim)
    }
    @Test fun roundingAllocatesExactlyAnnualTotal() {
        for (annual in listOf(26.0, 32.0, 68.0, 104.0, 100.0, 17.5)) {
            assertEquals(annual, (1..12).sumOf { engine.monthlyRate(annual, it) }, 0.00001)
        }
        assertEquals(2.16, engine.monthlyRate(26.0, 4), 0.0)
        assertEquals(2.17, engine.monthlyRate(26.0, 5), 0.0)
    }
    @Test fun fifteenthDayAndInitialDateAreBothGates() {
        val p = Profile(UserEntity("a", contractStart = "2026-09-15"))
        assertFalse(LeaveEngine(LocalDate.of(2026,9,14)).monthAccrues(p,2026,9))
        assertTrue(LeaveEngine(LocalDate.of(2026,9,15)).monthAccrues(p,2026,9))
        assertFalse(engine.monthAccrues(p.copy(user = p.user.copy(contractStart = "2026-09-16")),2026,9))
        assertFalse(engine.monthAccrues(p.copy(user = p.user.copy(initialDate = "2026-09-16")),2026,9))
        assertFalse(engine.monthAccrues(p,2026,10))
        assertTrue(LeaveEngine(today,YearMonth.of(2026,10)).monthAccrues(p,2026,10))
    }
    @Test fun ccnlUsesOriginal24And48MonthThresholds() {
        val p = Profile(UserEntity("a",calcMode=1.2,contractStart="2024-09-11"))
        assertEquals(engine.monthlyRate(32.0,8),engine.leaveRate(p,2026,8),0.0)
        assertEquals(engine.monthlyRate(68.0,9),engine.leaveRate(p,2026,9),0.0)
        assertEquals(engine.monthlyRate(104.0,9),engine.leaveRate(p,2028,9),0.0)
    }
    @Test fun matchesReadOnlyOriginalPwaOracle() {
        val p = Profile(UserEntity("a",calcMode=1.2,contractStart="2024-09-11",initialDate="2025-06-16",initialVacation=3.0,initialLeave=-4.0,initialTimeBank=7.5),
            listOf(YearConfigEntity("a",2025),YearConfigEntity("a",2026)),listOf(
                entry("1","ferie","2025-07-01",20.0),entry("2","permesso","2025-07-01",40.0),
                entry("3","permesso","2026-01-01",5.0),entry("4","permesso_pagato","2026-09-01",8.0),
                entry("5","ferie","2026-09-01",2.0,true),entry("6","banca_accumulo","2026-09-01",2.5)))
        // Values generated by tools/pwa-oracle.cjs directly from main:index.html.
        assertEquals(Amounts(0.0,-27.98),engine.previous(p,2026))
        assertEquals(Amounts(19.49,26.99),engine.annualAccrued(p,2026))
        val totals = engine.annualTotals(p,2026)
        assertEquals(Amounts(0.0,13.0),totals.currentUsed)
        assertEquals(Amounts(19.49,13.99),totals.currentRemaining)
        assertEquals(5.0,totals.currentEnjoyed,0.0)
        assertEquals(8.0,totals.currentPaid,0.0)
        val month = engine.monthBalance(p,2026,9,true)
        assertEquals(Amounts(17.32,-11.66),month.start)
        assertEquals(Amounts(17.09,-13.99),month.end)
        assertEquals(10.0,engine.timeBank(p,2026,9),0.0)
    }
    @Test fun fifoConsumesPreviousBalanceBeforeCurrentAndLiquidationConsumesLeave() {
        val p = Profile(UserEntity("a",initialDate="2026-01-01",initialVacation=4.0,initialLeave=10.0),entries=listOf(
            entry("1","ferie","2026-02-01",6.0),entry("2","permesso","2026-02-01",7.0),entry("3","permesso_pagato","2026-02-01",8.0)))
        val totals = engine.annualTotals(p,2026)
        assertEquals(Amounts(4.0,10.0),totals.previousUsed)
        assertEquals(Amounts(2.0,5.0),totals.currentUsed)
        assertEquals(7.0,totals.previousEnjoyed,0.0)
        assertEquals(3.0,totals.previousPaid,0.0)
        assertEquals(5.0,totals.currentPaid,0.0)
    }
    @Test fun simulationExcludesFutureMonthsAndDoesNotAlterOfficialHistory() {
        val p = Profile(UserEntity("a"),entries=listOf(entry("1","permesso","2026-09-01",2.0,true),entry("2","permesso","2026-10-01",9.0)))
        assertEquals(9.0,engine.yearUsed(p,2026).leave,0.0)
        val sim = LeaveEngine(today,YearMonth.of(2026,9))
        assertEquals(2.0,sim.yearUsed(p,2026,true).leave,0.0)
        assertEquals(0.0,sim.yearUsed(p,2026,false).leave,0.0)
    }
    @Test fun specialLeaveAndBankDoNotConsumeOrdinaryLeave() {
        val p = Profile(UserEntity("a",initialDate="2026-09-15"),entries=listOf(
            entry("1","permesso_104","2026-09-01",8.0),entry("2","permesso_studio","2026-09-20",6.0),
            entry("3","banca_accumulo","2026-09-20",3.0),entry("4","banca_fruizione","2026-09-21",1.0)))
        assertEquals(0.0,engine.yearUsed(p,2026).leave,0.0)
        assertEquals(0.0,engine.specialAnnual(p,"permesso_104",2026),0.0)
        assertEquals(8.0,engine.specialMonth(p,"permesso_104",2026,9),0.0)
        assertEquals(6.0,engine.specialAnnual(p,"permesso_studio",2026),0.0)
        assertEquals(2.0,engine.timeBank(p,2026,9),0.0)
        assertEquals(288.0,engine.law104AnnualBudget(p),0.0)
    }
    @Test fun holidaysWorkdaysAndCustomRecurrence() {
        val p = Profile(UserEntity("a"), holidays=WorkCalendar.defaultHolidays("a"))
        assertEquals(LocalDate.of(2026,4,6),WorkCalendar.easterMonday(2026))
        assertFalse(WorkCalendar.isWorkday(p,LocalDate.of(2026,4,6)))
        assertEquals(4,WorkCalendar.workdays(p,LocalDate.of(2026,4,6),LocalDate.of(2026,4,12)))
        val custom = p.copy(holidays=listOf(HolidayEntity("a","custom","Patrono",9,30,fromYear=2027)))
        assertFalse(WorkCalendar.isHoliday(custom,today))
        assertTrue(WorkCalendar.isHoliday(custom,today.plusYears(1)))
    }
}
